const mockData = [
    {
      id: 1,
      jobRequest: "Launch social media campaign for product launch",
      submitted: "15-11-2024",
      status: "In-process" as const,
      submitter: "Aisha Patel",
      submitterUrl: "www.aishapatel.com",
      url: "www.aishapatel.com",
      assigned: "Sophie Choudhury",
      priority: "Medium" as const,
      dueDate: "20-11-2024",
      estValue: 6200000,
    },
    {
      id: 2,
      jobRequest: "Update press kit for company redesign",
      submitted: "28-10-2024",
      status: "Need to start" as const,
      submitter: "Irfan Khan",
      submitterUrl: "www.irfankhang.com",
      url: "www.irfankhang.com",
      assigned: "Tejas Pandey",
      priority: "High" as const,
      dueDate: "30-10-2024",
      estValue: 3500000,
    },
    {
      id: 3,
      jobRequest: "Finalize user testing feedback for app redesign",
      submitted: "05-12-2024",
      status: "In-process" as const,
      submitter: "Mark Johnson",
      submitterUrl: "www.markjohns.com",
      url: "www.markjohns.com",
      assigned: "Rachel Lee",
      priority: "Medium" as const,
      dueDate: "10-12-2024",
      estValue: 4750000,
    },
    {
      id: 4,
      jobRequest: "Design new features for the website",
      submitted: "10-01-2025",
      status: "Complete" as const,
      submitter: "Emily Green",
      submitterUrl: "www.emilygreen.com",
      url: "www.emilygreen.com",
      assigned: "Tom Wright",
      priority: "Low" as const,
      dueDate: "15-01-2025",
      estValue: 5900000,
    },
    {
      id: 5,
      jobRequest: "Prepare financial report for Q4",
      submitted: "25-01-2025",
      status: "Blocked" as const,
      submitter: "Jessica Brown",
      submitterUrl: "www.jessicabrown.com",
      url: "www.jessicabrown.com",
      assigned: "Kevin Smith",
      priority: "Low" as const,
      dueDate: "30-01-2025",
      estValue: 2800000,
    },
  ]

export default mockData;